# Generated by Django 5.2.6 on 2025-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_account_educationalbackground_familybackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familybackground',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
