# Generated by Django 5.2.6 on 2025-11-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_familybackground_salary_alter_studentinfo_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingDatabase',
        ),
    ]
